--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#272725"
foreground="#bc9f67"
cursor="#282826"

-- Colors
color0="#272725"
color1="#7d5151"
color2="#959c4f"
color3="#a78749"
color4="#455563"
color5="#9f908d"
color6="#4a5e5b"
color7="#f2f2f2"
color8="#4f4f4b"
color9="#7d5151"
color10="#959c4f"
color11="#a78749"
color12="#455563"
color13="#9f908d"
color14="#4a5e5b"
color15="#ffffff"
