--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#272a2a"
foreground="#80807e"
cursor="#eaeaed"

-- Colors
color0="#272a2a"
color1="#b05f5f"
color2="#b05f5f"
color3="#88aa55"
color4="#88aa55"
color5="#ccb05f"
color6="#ccb05f"
color7="#556973"
color8="#484c4e"
color9="#b05f5f"
color10="#b05f5f"
color11="#88aa55"
color12="#88aa55"
color13="#ccb05f"
color14="#ccb05f"
color15="#f6f7f8"
