--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#272c30"
foreground="#c79e84"
cursor="#cfb9a8"

-- Colors
color0="#272c30"
color1="#934e46"
color2="#637268"
color3="#c79e84"
color4="#515e67"
color5="#715f5e"
color6="#5c6f7d"
color7="#cfb9a8"
color8="#414a51"
color9="#934e46"
color10="#637268"
color11="#c79e84"
color12="#515e67"
color13="#715f5e"
color14="#5c6f7d"
color15="#ddcec2"
